# Generated by Django 2.2.2 on 2019-06-16 04:13

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False, verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='securityquestion1',
            field=models.CharField(max_length=20, null=True, verbose_name='Security question 1: What is the name of hospital were you born in?'),
        ),
        migrations.AddField(
            model_name='user',
            name='securityquestion2',
            field=models.CharField(max_length=20, null=True, verbose_name='Securtiy question 2: What was your childhood friends name?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Confirm email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A email with that username already exists.'}, help_text='Required. Inform a valid email address.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='email'),
        ),
    ]
